In [1]:
from vaccination_functions import *
#from acs_data_functions import *

In [2]:
data_path = "../feature_inputs/"

enroll_regr_rand = pd.read_csv(data_path+"tea_districts_enroll_percent_regression_rand.csv")
enroll_sal_regr_rand = pd.read_csv(data_path+"tea_districts_enroll_percent_staff_salary_regression_rand.csv")
enroll_regr_half = pd.read_csv(data_path+"tea_districts_enroll_percent_regression.csv")
enroll_sal_regr_half = pd.read_csv(data_path+"tea_districts_enroll_percent_staff_salary_regression.csv")

In [5]:
tea_drop_columns = ['County_Name', 'District_Name', 'Total_Count']
tea_drop_columns_corr = ['County_Name', 'District_Name', 'Total_Count', 'MMR Vaccination Rate']

In [6]:
enroll_half_num_feats_dict, enroll_half_corr_reduced, enroll_half_corr_dropped_cols = determine_corr_feats(enroll_regr_half, tea_drop_columns_corr)

24 intital features, reduced to 23 features

In [7]:
enroll_sal_half_num_feats_dict, enroll_sal_half_corr_reduced, enroll_sal_half_corr_dropped_cols = determine_corr_feats(enroll_sal_regr_half, tea_drop_columns_corr)

27 intital features, reduced to 25 features

In [8]:
enroll_rand_num_feats_dict, enroll_rand_corr_reduced, enroll_rand_corr_dropped_cols = determine_corr_feats(enroll_regr_rand, tea_drop_columns_corr)

24 intital features, reduced to 23 features

In [9]:
enroll_sal_rand_num_feats_dict, enroll_sal_rand_corr_reduced, enroll_sal_rand_corr_dropped_cols = determine_corr_feats(enroll_sal_regr_rand, tea_drop_columns_corr)

27 intital features, reduced to 25 features

Replacing Unknowns with Half the Max Limit

In [6]:
enroll_ridge_half_results_df, enroll_ridge_half_dict, enroll_ridge_half_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_regr_half, model_type="Ridge", drop_columns=tea_drop_columns)
enroll_ridge_half_results_df.head()

R2 = 0.09248721101388035, MAE = 4.104771244060344, RMSE = 6.771136489508976

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,0.041611,-0.130285,0.236054,Not Signficant
1,Male,-0.041611,-0.236054,0.130285,Not Signficant
2,American Indian or Alaska Nat,0.115657,-0.496834,0.710426,Not Signficant
3,Asian,0.017903,-0.481392,0.550558,Not Signficant
4,Black or African American,-0.725722,-2.199394,0.671422,Not Signficant

In [7]:
enroll_salary_ridge_half_results_df, enroll_salary_ridge_half_perf_dict, enroll_salary_ridge_half_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_sal_regr_half, model_type="Ridge", drop_columns=tea_drop_columns)
enroll_salary_ridge_half_results_df.head()

R2 = 0.1174761248196643, MAE = 3.4491645432487217, RMSE = 5.828923087710139

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,-0.007240,-0.033233,0.017575,Not Signficant
1,Male,0.007240,-0.017575,0.033233,Not Signficant
2,American Indian or Alaska Nat,0.102803,0.059076,0.148184,Signficant
3,Asian,0.019800,-0.051702,0.096237,Not Signficant
4,Black or African American,-0.533457,-0.724680,-0.325499,Signficant

In [8]:
enroll_linear_half_results_df, enroll_linear_half_perf_dict, enroll_linear_half_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_regr_half, model_type="Linear", drop_columns=tea_drop_columns)
enroll_linear_half_results_df.head()

R2 = 0.06470471071604655, MAE = 4.000301668982964, RMSE = 6.518548883396058

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,-0.001289,-0.194829,0.217534,Not Signficant
1,Male,0.001289,-0.217534,0.194829,Not Signficant
2,American Indian or Alaska Nat,0.183351,-0.259185,0.539960,Not Signficant
3,Asian,0.153221,-0.425672,0.775167,Not Signficant
4,Black or African American,-0.412943,-1.997919,1.244707,Not Signficant

In [9]:
enroll_salary_linear_half_results_df, enroll_salary_linear_half_perf_dict, enroll_salary_linear_half_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_sal_regr_half, model_type="Linear", drop_columns=tea_drop_columns)
enroll_salary_linear_half_results_df.head()

R2 = 0.11605986097805376, MAE = 3.4164232289107077, RMSE = 5.590211648460807

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,-0.003490,-0.030998,0.023556,Not Signficant
1,Male,0.003490,-0.023556,0.030998,Not Signficant
2,American Indian or Alaska Nat,0.098297,0.054077,0.141370,Signficant
3,Asian,0.019004,-0.059970,0.094853,Not Signficant
4,Black or African American,-0.525649,-0.733945,-0.335364,Signficant

Replacing Unknowns with Random Generated Number

In [10]:
enroll_ridge_rand_results_df, enroll_ridge_rand_dict, enroll_ridge_rand_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_regr_rand, model_type="Ridge", drop_columns=tea_drop_columns)
enroll_ridge_rand_results_df.head()

R2 = 0.07265355329947676, MAE = 3.8686918130314125, RMSE = 5.755975537907229

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,0.057374,-0.130780,0.259609,Not Signficant
1,Male,-0.057374,-0.259609,0.130780,Not Signficant
2,American Indian or Alaska Nat,0.132819,-0.280269,0.478602,Not Signficant
3,Asian,0.185542,-0.201754,0.718699,Not Signficant
4,Black or African American,-0.480332,-1.698554,0.816475,Not Signficant

In [11]:
enroll_salary_ridge_rand_results_df, enroll_salary_ridge_rand_perf_dict, enroll_salary_ridge_rand_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_sal_regr_rand, model_type="Ridge", drop_columns=tea_drop_columns)
enroll_salary_ridge_rand_results_df.head()

R2 = 0.11899095661173753, MAE = 3.3781397417586887, RMSE = 5.574477857936903

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,-0.013612,-0.039294,0.010285,Not Signficant
1,Male,0.013612,-0.010285,0.039294,Not Signficant
2,American Indian or Alaska Nat,0.069828,0.028841,0.111760,Signficant
3,Asian,0.118449,0.058014,0.179124,Signficant
4,Black or African American,-0.341290,-0.492589,-0.174798,Signficant

In [12]:
enroll_linear_rand_results_df, enroll_linear_rand_perf_dict, enroll_linear_rand_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_regr_rand, model_type="Linear", drop_columns=tea_drop_columns)
enroll_linear_rand_results_df.head()

R2 = -0.10953401367900018, MAE = 3.86551075148775, RMSE = 5.544441262130074

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,0.061882,-0.133896,0.244616,Not Signficant
1,Male,-0.061882,-0.244616,0.133896,Not Signficant
2,American Indian or Alaska Nat,0.246527,-0.064745,0.627417,Not Signficant
3,Asian,0.354927,-0.139231,0.946464,Not Signficant
4,Black or African American,-0.213346,-1.589947,1.308060,Not Signficant

In [13]:
enroll_salary_linear_rand_results_df, enroll_salary_linear_rand_perf_dict, enroll_salary_linear_rand_vac_rates_dict = bootstrap_confidence_interval(1000, enroll_sal_regr_rand, model_type="Linear", drop_columns=tea_drop_columns)
enroll_salary_linear_rand_results_df.head()

R2 = 0.10995254049084724, MAE = 3.4013012283480357, RMSE = 5.666490878421034

,Predictor,Mean,CI_Lower,CI_Upper,Coeff Signficance
0,Female,-0.006053,-0.032894,0.016928,Not Signficant
1,Male,0.006053,-0.016928,0.032894,Not Signficant
2,American Indian or Alaska Nat,0.090181,0.050097,0.126166,Signficant
3,Asian,0.131815,0.067381,0.194324,Signficant
4,Black or African American,-0.373365,-0.530673,-0.213541,Signficant