In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import seaborn as sns

In [2]:
from vaccination_functions import *

In [3]:
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.feature_selection import f_regression

In [4]:
tx_mmr_vac_rates = pd.read_csv("../TX_MMR_vax_rate_24_25.csv")
counties_with_vac = tx_mmr_vac_rates['County'].unique()

In [ ]:
acs_data_path = "../acs_data/"

In [ ]:
age_df = pd.read_csv(acs_data_path+"tx_county_agePop_24.csv")
age_var_df = pd.read_csv(acs_data_path+"ageVars_acs.csv")

race_df = pd.read_csv(acs_data_path+"x_county_racePop_24.csv")
race_var_df = pd.read_csv(acs_data_path+"raceVars_acs.csv")

education_df = pd.read_csv(acs_data_path+"tx_county_education_24.csv")
education_var_df = pd.read_csv(acs_data_path+"educationVars_acs.csv")

enrollment_df = pd.read_csv(acs_data_path+"tx_county_enrollment_24.csv")
enrollment_var_df = pd.read_csv(acs_data_path+"enrollmentVars_acs.csv")

poverty_df = pd.read_csv(acs_data_path+"tx_county_poverty_24.csv")
poverty_var_df = pd.read_csv(acs_data_path+"povertyVars_acs.csv")

In [6]:
age_with_var_all, age_with_var_no_gender = create_predictor_datasets(age_df, age_var_df, counties_with_vac)
race_with_var_all, race_with_var_no_gender = create_predictor_datasets(race_df, race_var_df, counties_with_vac)
education_with_var_all, education_with_var_no_gender = create_predictor_datasets(education_df, education_var_df, counties_with_vac)
enrollment_with_var_all, enrollment_with_var_no_gender = create_predictor_datasets(enrollment_df, enrollment_var_df, counties_with_vac)
poverty_with_var_all, poverty_with_var_no_gender = create_predictor_datasets(poverty_df, poverty_var_df, counties_with_vac)

In [7]:
age_with_var_no_gender['Estimate_Total_Under_5'] = age_with_var_all['Estimate_Total_Male_Under_5'] + age_with_var_all['Estimate_Total_Female_Under_5']
age_with_var_no_gender['Estimate_Total_5_9'] = age_with_var_all['Estimate_Total_Male_5_9'] + age_with_var_all['Estimate_Total_Female_5_9']
age_with_var_no_gender['Estimate_Total_10_14'] = age_with_var_all['Estimate_Total_Male_10_14'] + age_with_var_all['Estimate_Total_Female_10_14']
age_with_var_no_gender['Estimate_Total_15_17'] = age_with_var_all['Estimate_Total_Male_15_17'] + age_with_var_all['Estimate_Total_Female_15_17']
age_with_var_no_gender['Estimate_Total_18_19'] = age_with_var_all['Estimate_Total_Male_18_and_19'] + age_with_var_all['Estimate_Total_Female_18_and_19']
age_with_var_no_gender['Estimate_Total_21'] = age_with_var_all['Estimate_Total_Male_21'] + age_with_var_all['Estimate_Total_Female_21']
age_with_var_no_gender['Estimate_Total_22_24'] = age_with_var_all['Estimate_Total_Male_22_24'] + age_with_var_all['Estimate_Total_Female_22_24']
age_with_var_no_gender['Estimate_Total_25_29'] = age_with_var_all['Estimate_Total_Male_25_29'] + age_with_var_all['Estimate_Total_Female_25_29']
age_with_var_no_gender['Estimate_Total_30_34'] = age_with_var_all['Estimate_Total_Male_30_34'] + age_with_var_all['Estimate_Total_Female_30_34']
age_with_var_no_gender['Estimate_Total_35_39'] = age_with_var_all['Estimate_Total_Male_35_39'] + age_with_var_all['Estimate_Total_Female_35_39']

In [8]:
age_with_var_no_gender['Estimate_Total_40_44'] = age_with_var_all['Estimate_Total_Male_40_44'] + age_with_var_all['Estimate_Total_Female_40_44']
age_with_var_no_gender['Estimate_Total_45_49'] = age_with_var_all['Estimate_Total_Male_45_49'] + age_with_var_all['Estimate_Total_Female_45_49']
age_with_var_no_gender['Estimate_Total_50_54'] = age_with_var_all['Estimate_Total_Male_50_54'] + age_with_var_all['Estimate_Total_Female_50_54']
age_with_var_no_gender['Estimate_Total_55_59'] = age_with_var_all['Estimate_Total_Male_55_59'] + age_with_var_all['Estimate_Total_Female_55_59']
age_with_var_no_gender['Estimate_Total_60_61'] = age_with_var_all['Estimate_Total_Male_60_and_61'] + age_with_var_all['Estimate_Total_Female_60_and_61']
age_with_var_no_gender['Estimate_Total_62_64'] = age_with_var_all['Estimate_Total_Male_62_64'] + age_with_var_all['Estimate_Total_Female_62_64']
age_with_var_no_gender['Estimate_Total_65_66'] = age_with_var_all['Estimate_Total_Male_65_and_66'] + age_with_var_all['Estimate_Total_Female_65_and_66']
age_with_var_no_gender['Estimate_Total_67_69'] = age_with_var_all['Estimate_Total_Male_67_69'] + age_with_var_all['Estimate_Total_Female_67_69']
age_with_var_no_gender['Estimate_Total_70_74'] = age_with_var_all['Estimate_Total_Male_70_74'] + age_with_var_all['Estimate_Total_Female_70_74']
age_with_var_no_gender['Estimate_Total_75_79'] = age_with_var_all['Estimate_Total_Male_75_79'] + age_with_var_all['Estimate_Total_Female_75_79']
age_with_var_no_gender['Estimate_Total_80_84'] = age_with_var_all['Estimate_Total_Male_80_84'] + age_with_var_all['Estimate_Total_Female_80_84']
age_with_var_no_gender['Estimate_Total_85_over'] = age_with_var_all['Estimate_Total_Male_85_and_over'] + age_with_var_all['Estimate_Total_Female_85_and_over']

In [9]:
age_with_var_all_percent, age_with_var_no_gender_percent = create_predictor_percentages(age_with_var_all, age_with_var_no_gender)
race_with_var_all_percent, race_with_var_no_gender_percent = create_predictor_percentages(race_with_var_all, race_with_var_no_gender)
education_with_var_all_percent, education_with_var_no_gender_percent = create_predictor_percentages(education_with_var_all, education_with_var_no_gender)
enrollment_with_var_all_percent, enrollment_with_var_no_gender_percent = create_predictor_percentages(enrollment_with_var_all, enrollment_with_var_no_gender)

In [10]:
### Predictor datasets with vaccination rates for percentages
race_vac_set_all_percent, race_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, race_with_var_all_percent, race_with_var_no_gender_percent)
age_vac_set_all, age_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, age_with_var_all_percent, age_with_var_no_gender_percent)
education_vac_set_all_percent, education_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, education_with_var_all_percent, education_with_var_no_gender_percent)
enrollment_vac_set_all_percent, enrollment_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, enrollment_with_var_all_percent, enrollment_with_var_no_gender_percent)

c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:93: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  single_pred_df_all = pd.merge(predictor_df_all, vac_df_rel, on=['County'])

In [11]:
all_acs_variables_percent = combine_all_acs_variables(education_with_var_all_percent, race_with_var_all_percent, enrollment_with_var_all_percent, age_with_var_all_percent, poverty_with_var_all, percent=True, gender=True)
all_acs_variables_no_gender_percent = combine_all_acs_variables(education_with_var_no_gender_percent, race_with_var_no_gender_percent, enrollment_with_var_no_gender_percent, age_with_var_no_gender_percent, poverty_with_var_all, percent=True)
all_vac_set_percent, all_vac_set_no_gender_percent = vac_predictor_merge(tx_mmr_vac_rates, all_acs_variables_percent, all_acs_variables_no_gender_percent)

c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:105: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  edu_race_df = pd.merge(edu_df.drop(columns=['Estimate_Total', 'B15003_025', 'Percent_Male', 'Percent_Female']), race_df.drop(columns=['Estimate_Total']), on=['County'])
c:\Users\19037\Documents\Measels_Vaccination\code_backup\vaccination_functions.py:107: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_acs_variables = pd.merge(pd.merge(edu_race_df, enroll_age_df, on=['County']), poverty_df, on=['County'])

## PCA Code Development for vaccination_functions.py

In [12]:
n = 10
scaler = MinMaxScaler()
pca_model = PCA(n_components=n)
y_data = all_vac_set_no_gender_percent['MMR Vaccination Rate']
x_data = all_vac_set_no_gender_percent.drop(columns=['MMR Vaccination Rate', 'County'])
x_scaler = scaler.fit_transform(x_data)
x_pca = pca_model.fit_transform(x_scaler)
#modelR = Ridge(alpha=1.0).fit(x_pca, y_data)

In [72]:
coef_list= []
for i in range(10):
    x_boot, y_boot = resample(x_pca, y_data)
    modelR = Ridge(alpha=1.0).fit(x_boot, y_boot)
    coef_list.append(modelR.coef_)

In [73]:
component_names = ['PC'+str(x) for x in range(n)]
df = pd.DataFrame(coef_list,  columns=component_names)

In [74]:
ci_lower = np.percentile(df, 2.5, axis=0)
ci_upper = np.percentile(df, 97.5, axis=0)
coef_mean = np.mean(df, axis=0).to_numpy()

ci_results_df = pd.DataFrame({'Predictor': component_names,
                                            'Mean': coef_mean,
                                            'CI_Lower': ci_lower,
                                            'CI_Upper': ci_upper})
    
ci_results_df["Explained Variance"] = pca_model.explained_variance_ratio_
ci_results_df['Coeff Signficance'] = ['Not Signficant' if l <= 0 <= u else 'Signficant' for l,u in zip(ci_results_df['CI_Lower'], ci_results_df['CI_Upper'])]

In [75]:
ci_results_df

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PC0,-0.963287,-1.566031,-0.592982,0.387142,Signficant
1,PC1,-4.315649,-5.077795,-3.242774,0.146853,Signficant
2,PC2,0.903437,0.096109,1.916642,0.094867,Signficant
3,PC3,0.594967,-0.213793,1.608221,0.052322,Not Signficant
4,PC4,-0.394892,-1.712504,0.706513,0.034868,Not Signficant
5,PC5,-3.932990,-4.557611,-2.801281,0.028590,Signficant
6,PC6,0.194885,-0.802084,1.469780,0.022606,Not Signficant
7,PC7,3.062553,1.525435,4.833905,0.018589,Signficant
8,PC8,1.789361,-0.639588,3.703858,0.015336,Not Signficant
9,PC9,-3.259760,-5.973463,-1.976963,0.012134,Signficant

In [77]:
x_pca

array([[-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       [-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       [-0.53196273, -0.0601421 ,  0.34766703, ..., -0.11764175,
        -0.04990058, -0.02983319],
       ...,
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104],
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104],
       [-0.29969   , -1.23464949, -0.60533858, ...,  0.35480156,
        -0.21762784, -0.00364104]], shape=(3082, 10))

In [79]:
pc_df = pd.DataFrame(x_pca, columns=component_names)
pc_df

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
0,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
1,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
2,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
3,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
4,-0.531963,-0.060142,0.347667,0.275815,-0.242300,-0.602543,-0.202397,-0.117642,-0.049901,-0.029833
...,...,...,...,...,...,...,...,...,...,...
3077,-0.129009,-1.231920,-0.780149,-0.375005,-0.105225,0.106729,0.145727,0.392482,-0.008380,-0.160790
3078,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641
3079,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641
3080,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641
3081,-0.299690,-1.234649,-0.605339,-0.303282,-0.072335,-0.191885,-0.048245,0.354802,-0.217628,-0.003641

In [85]:
sig_predictors = ci_results_df[ci_results_df['Coeff Signficance'] == 'Signficant']['Predictor']
#ci_results_df[ci_results_df['Coeff Signficance'] == 'Signficant']['Predictor']

In [88]:
pc_df_sig = pc_df[sig_predictors]
pc_df_sig['MMR'] = y_data
pc_df_sig

           PC0       PC1       PC2       PC5       PC7       PC9     MMR
0    -0.531963 -0.060142  0.347667 -0.602543 -0.117642 -0.029833   90.24
1    -0.531963 -0.060142  0.347667 -0.602543 -0.117642 -0.029833   93.00
2    -0.531963 -0.060142  0.347667 -0.602543 -0.117642 -0.029833   96.23
3    -0.531963 -0.060142  0.347667 -0.602543 -0.117642 -0.029833   93.75
4    -0.531963 -0.060142  0.347667 -0.602543 -0.117642 -0.029833   96.28
...        ...       ...       ...       ...       ...       ...     ...
3077 -0.129009 -1.231920 -0.780149  0.106729  0.392482 -0.160790  100.00
3078 -0.299690 -1.234649 -0.605339 -0.191885  0.354802 -0.003641  100.00
3079 -0.299690 -1.234649 -0.605339 -0.191885  0.354802 -0.003641  100.00
3080 -0.299690 -1.234649 -0.605339 -0.191885  0.354802 -0.003641  100.00
3081 -0.299690 -1.234649 -0.605339 -0.191885  0.354802 -0.003641  100.00

[3082 rows x 7 columns]

In [92]:
coef_list2 = []
for i in range(10):
    x_boot2, y_boot2 = resample(pc_df_sig.drop(columns='MMR'), pc_df_sig['MMR'])
    modelR_2 = Ridge(alpha=1.0).fit(x_boot2, y_boot2)
    coef_list2.append(modelR_2.coef_)

In [96]:
#coef_list2
coef_df2 = pd.DataFrame(coef_list2, columns=pc_df_sig.drop(columns='MMR').columns)
#coef_df2
ci_lower2 = np.percentile(coef_df2, 2.5, axis=0)
ci_upper2 = np.percentile(coef_df2, 97.5, axis=0)
coef_mean2 = np.mean(coef_df2, axis=0).to_numpy()

ci_results_df2 = pd.DataFrame({'Predictor': pc_df_sig.drop(columns='MMR').columns,
                                            'Mean': coef_mean2,
                                            'CI_Lower': ci_lower2,
                                            'CI_Upper': ci_upper2})
    
ci_results_df2['Coeff Signficance'] = ['Not Signficant' if l <= 0 <= u else 'Signficant' for l,u in zip(ci_results_df2['CI_Lower'], ci_results_df2['CI_Upper'])]

ci_results_df2

  Predictor      Mean  CI_Lower  CI_Upper Coeff Signficance
0       PC0 -0.823422 -1.336904 -0.254379        Signficant
1       PC1 -4.763591 -6.057674 -3.486590        Signficant
2       PC2  1.231788  0.611045  2.098301        Signficant
3       PC5 -3.195080 -4.405657 -2.103202        Signficant
4       PC7  3.145578  1.584391  4.876722        Signficant
5       PC9 -2.649997 -4.890700 -1.091059        Signficant

In [68]:
x_pca[:,0]

array([-0.53196273, -0.53196273, -0.53196273, ..., -0.29969   ,
       -0.29969   , -0.29969   ], shape=(3082,))

In [70]:
x_pca[:,:3]

array([[-0.53196273, -0.0601421 ,  0.34766703],
       [-0.53196273, -0.0601421 ,  0.34766703],
       [-0.53196273, -0.0601421 ,  0.34766703],
       ...,
       [-0.29969   , -1.23464949, -0.60533858],
       [-0.29969   , -1.23464949, -0.60533858],
       [-0.29969   , -1.23464949, -0.60533858]], shape=(3082, 3))

In [18]:
x_pca

array([[-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
       ...,
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
       [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464]],
      shape=(3082, 5))

In [52]:
num_components = x_pca.shape[1]

In [56]:
cols = ['PCA'+str(x) for x in range(num_components)]
cols

['PCA0', 'PCA1', 'PCA2', 'PCA3', 'PCA4']

In [29]:
[y_data.values, x_pca]

[array([ 90.24,  93.  ,  96.23, ..., 100.  , 100.  , 100.  ], shape=(3082,)),
 array([[-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        [-0.53196273, -0.0601421 ,  0.34766703,  0.27581545, -0.24230018],
        ...,
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464],
        [-0.29969   , -1.23464949, -0.60533858, -0.303282  , -0.07233464]],
       shape=(3082, 5))]

In [37]:
coef_df = pd.DataFrame(x_pca,  columns=['PCA1', 'PCA2', 'PCA3', 'PCA4', 'PCA5'])

In [38]:
coef_df['Measels_Vac_Rate'] = y_data.values

In [39]:
coef_df

          PCA1      PCA2      PCA3      PCA4      PCA5  Measels_Vac_Rate
0    -0.531963 -0.060142  0.347667  0.275815 -0.242300             90.24
1    -0.531963 -0.060142  0.347667  0.275815 -0.242300             93.00
2    -0.531963 -0.060142  0.347667  0.275815 -0.242300             96.23
3    -0.531963 -0.060142  0.347667  0.275815 -0.242300             93.75
4    -0.531963 -0.060142  0.347667  0.275815 -0.242300             96.28
...        ...       ...       ...       ...       ...               ...
3077 -0.129009 -1.231920 -0.780149 -0.375005 -0.105225            100.00
3078 -0.299690 -1.234649 -0.605339 -0.303282 -0.072335            100.00
3079 -0.299690 -1.234649 -0.605339 -0.303282 -0.072335            100.00
3080 -0.299690 -1.234649 -0.605339 -0.303282 -0.072335            100.00
3081 -0.299690 -1.234649 -0.605339 -0.303282 -0.072335            100.00

[3082 rows x 6 columns]

In [43]:
coef_list = []
for i in range(100):
    x_boot, y_boot = resample(x_pca, y_data)
    model = Ridge(alpha=1.0).fit(x_boot, y_boot)

    coef_list.append(model.coef_)

In [44]:
coef_list

[array([-0.58368312, -3.86847023,  0.4158315 , -0.51401088,  0.35238539]),
 array([-1.03458772, -4.4188667 ,  0.69695081, -0.85371833, -0.6507871 ]),
 array([-1.16973629, -3.69049483,  3.10514929,  0.44331896, -0.39009034]),
 array([-1.04484519, -4.58190042,  0.79644704,  0.59800928, -0.72919818]),
 array([-0.79971969, -4.82903469,  1.36092854,  1.07714456,  1.12889121]),
 array([-1.04167992, -4.3829248 ,  2.0409906 , -0.03890884, -0.52266628]),
 array([-0.3766142 , -4.76449358,  0.97149669, -0.17781623, -0.09126731]),
 array([-0.00646861, -4.37731753,  1.01544892,  0.66519749,  1.09090201]),
 array([-0.74050573, -4.80891014,  2.08386223, -0.40397605,  0.4353146 ]),
 array([-1.38877239, -5.40775072,  0.52106451,  1.43850701, -1.81776062]),
 array([-1.25898263, -4.11505185,  1.58622827,  0.06658805, -0.94076593]),
 array([-0.94629873, -5.32576001,  1.38560534,  1.18419913,  0.63398907]),
 array([-0.52388188, -3.93496299,  1.13862769,  0.58482055,  0.40759769]),
 array([-0.81523679, -4.67117202,  1.33215671,  0.66980002,  0.08738924]),
 array([-1.66594087, -4.24446897,  0.35340865, -0.47226243, -0.38190726]),
 array([-0.66644273, -4.69217072,  2.23535558,  0.29264272, -0.8193875 ]),
 array([-0.64299032, -4.18124775,  1.41742799,  0.66238568, -0.29789002]),
 array([-0.77714568, -4.25430241,  0.66023398,  0.56995241,  0.29472687]),
 array([-1.46178275, -4.97533049,  1.62086079,  0.40428793, -1.84345713]),
 array([-0.79894954, -4.7846167 ,  0.84053738, -0.61562216,  1.20619405]),
 array([-0.85251707, -4.613446  ,  1.01734977,  0.6227997 ,  0.83743075]),
 array([-0.66526788, -4.75899731,  1.45372995,  0.7652017 ,  0.14891417]),
 array([-0.59301767, -4.86949087,  1.51309014, -0.74486085, -0.51569564]),
 array([-4.92245845e-01, -4.83544755e+00,  1.09150187e+00,  2.15465936e-01,
        -2.60645589e-03]),
 array([-0.5222723 , -4.44472508,  1.81729862,  0.35177055,  0.20291603]),
 array([-1.32428152, -3.82848166,  0.42360893, -0.25274918, -0.38934924]),
 array([-0.82420715, -5.05937612,  2.03315066,  2.00308168, -0.23384928]),
 array([-1.07018367, -4.81217669,  1.60036546,  0.22714236, -0.14844696]),
 array([-0.39598953, -4.73721187,  1.14104736,  0.66880573,  0.62037708]),
 array([-0.49880811, -3.69360515,  0.93944003,  0.53540855, -0.16402066]),
 array([-1.26039813, -5.11873893,  0.7723481 ,  0.03069525, -0.04881437]),
 array([-1.2073151 , -4.85053451,  0.48440437, -0.61048409,  2.20719753]),
 array([-0.93328125, -4.84100076,  1.35717543,  0.78588879, -0.89012979]),
 array([-0.88746403, -4.51303343, -0.02987808,  0.52608005,  0.01756182]),
 array([-0.78352911, -4.67171566,  0.85321709,  0.92620033, -0.48937374]),
 array([-0.56755886, -4.45698728,  1.46429974,  0.98046748,  0.26841117]),
 array([-0.70372996, -4.30181875,  1.13304082, -0.49313649, -0.09541162]),
 array([-0.79302112, -3.9470792 ,  0.53670977,  0.97878283, -1.18003134]),
 array([-0.96528312, -4.95801603,  1.46660784, -0.63818666, -0.90526781]),
 array([-0.79745425, -4.78182471, -0.23000438,  0.44032999, -1.56141408]),
 array([-0.53550823, -4.08582662,  1.63591229, -0.15592579, -0.31983454]),
 array([-0.90190105, -4.86274222,  0.55905235, -0.17607499,  0.4862477 ]),
 array([-0.97240269, -4.7061472 ,  0.9757846 ,  0.13345779, -1.48258873]),
 array([-1.12309226, -4.4414634 ,  0.64683266,  0.48000576, -0.67448925]),
 array([-0.95690648, -4.275709  ,  1.7049855 ,  0.24152183, -0.68944944]),
 array([-0.69152428, -5.04874528,  1.41064348,  0.52912572,  0.19318502]),
 array([-0.85257842, -4.62195465,  0.48298831, -0.0539444 ,  0.7914633 ]),
 array([-0.88751981, -4.01398955,  1.134377  , -0.35373925, -2.02066222]),
 array([-0.78772841, -4.90936746,  0.54963266,  0.38709253,  1.72619568]),
 array([-0.57696188, -4.19177801,  1.54804725,  1.55992465,  0.02282867]),
 array([-0.8477645 , -5.10431584,  1.17236437,  0.9507662 , -0.49933641]),
 array([-0.69568409, -4.82608536,  1.60610138,  1.29051498,  0.51898308]),
 array([-0.90001876, -5.76982903,  1.0236444 ,  1.07226627, -0.03445506]),
 array([-0.85946404, -4.2243627 ,  1.27899778,  1.09499853,  1.11067423]),
 array([-0.95029417, -4.4429318 ,  2.12937185,  0.96652197,  0.20326719]),
 array([-1.30233397, -4.26048897,  0.94303741,  1.02910835, -0.69840013]),
 array([-0.81289094, -4.19834599,  0.75197387, -0.52173648, -1.69691447]),
 array([-0.84109854, -3.75013984,  1.81738478, -0.03567022, -0.73638313]),
 array([-1.21192077, -4.20269231,  1.19697248, -0.19701885, -0.88697213]),
 array([-0.82297242, -3.56497722,  1.28503393,  0.341196  , -0.45504963]),
 array([-0.31144323, -4.07893048,  1.30171358,  0.62595787, -0.51010674]),
 array([-8.46472089e-01, -5.62609671e+00,  1.31848073e+00,  2.43765840e-03,
         1.31864182e+00]),
 array([-0.63043941, -5.09500389,  1.32558079,  0.16961727, -0.45017969]),
 array([-1.12673693, -4.80101778,  1.10687865,  0.30852624,  1.51183531]),
 array([-1.02936617, -4.89215462,  0.34255614,  0.14171468,  0.18185379]),
 array([-0.42587862, -5.00214095,  1.22055268, -0.629548  , -0.91086024]),
 array([-1.29826581, -5.03557906,  1.17371589,  0.30640435, -0.08115953]),
 array([-0.65384014, -5.1995544 ,  1.78560741, -0.31808134,  0.51257952]),
 array([-1.19496747, -4.93117105,  1.93165169, -0.07677832,  0.56456353]),
 array([-0.74238547, -4.28785686,  1.23876527,  0.08455415, -0.49928844]),
 array([-0.361762  , -4.11290148,  2.02029723,  0.17301468, -0.1539841 ]),
 array([-1.05815318, -4.11391395,  1.08173938,  0.57669397,  0.67709223]),
 array([-0.72799181, -4.30359505,  1.76862401, -0.29152114, -0.82073169]),
 array([-0.8951361 , -4.95605046,  0.73812277, -0.14643879, -0.98379068]),
 array([-0.95034762, -4.23040335,  0.38820854,  0.20127316, -0.26370781]),
 array([-0.47908431, -4.31243261,  1.11921112,  0.23001803,  0.46590275]),
 array([-1.1242155 , -3.68722048,  0.8340864 ,  0.45433495, -0.47485016]),
 array([-0.7458379 , -4.89200418,  0.39913279, -0.04857467, -0.72047862]),
 array([-1.26505038, -4.76023712,  1.9774059 ,  0.67549502,  0.18405165]),
 array([-0.68628556, -4.88119366,  1.36550139, -0.82334277,  0.64436464]),
 array([-1.03668144, -4.51468132,  0.88505741, -0.91678613,  0.48122152]),
 array([-1.24975511, -4.94141015,  1.81218218,  0.45417998, -1.21969931]),
 array([-1.06340736, -5.40806404,  0.84143023,  0.61654837, -1.76978839]),
 array([-0.71612339, -4.65904211,  1.62785043, -0.30804487, -1.0257616 ]),
 array([-1.10527037, -5.60716819,  1.65607651,  1.08133409, -0.98580557]),
 array([-0.41611537, -3.87857027,  0.0837329 , -0.12696079,  0.66067598]),
 array([-1.42889466, -4.06948713,  1.09740943, -0.36485038,  1.25774945]),
 array([-1.8273619 , -3.82374477,  0.76010697, -0.60232486,  0.50721132]),
 array([-0.58823101, -4.61213256,  0.31833921,  0.23654706, -0.61484252]),
 array([-1.15015206, -4.6244994 ,  1.50637383,  0.66433789, -1.55121038]),
 array([-0.32574777, -5.17126156,  0.11716962,  0.30331734, -0.9614949 ]),
 array([-1.17128004, -4.0555273 ,  0.72178003, -1.15200646, -0.39257023]),
 array([-0.73349381, -4.22492468,  0.91895264, -0.46678702, -2.32886848]),
 array([-0.74030037, -4.77696965,  1.81747385, -0.36898986, -0.41250501]),
 array([-1.25642909, -5.0127848 ,  0.86021663, -0.22542951,  0.69306221]),
 array([-0.85678168, -4.27291566,  1.36558493, -0.40995521, -1.66982904]),
 array([-0.84071958, -3.90029932,  2.46164955,  2.22046888,  0.44648766]),
 array([-0.75730222, -4.52085564,  2.05435642,  1.00996193,  0.51725096]),
 array([-1.21932019, -4.94080968,  0.21430678,  0.44233501, -2.79117395]),
 array([-0.99847188, -4.7548337 ,  1.86980715, -0.12238232, -0.42716284])]

In [46]:
coef_df_2 = pd.DataFrame(coef_list, columns=coef_df.drop(columns="Measels_Vac_Rate").columns)

In [47]:
coef_df_2

        PCA1      PCA2      PCA3      PCA4      PCA5
0  -0.583683 -3.868470  0.415832 -0.514011  0.352385
1  -1.034588 -4.418867  0.696951 -0.853718 -0.650787
2  -1.169736 -3.690495  3.105149  0.443319 -0.390090
3  -1.044845 -4.581900  0.796447  0.598009 -0.729198
4  -0.799720 -4.829035  1.360929  1.077145  1.128891
..       ...       ...       ...       ...       ...
95 -0.856782 -4.272916  1.365585 -0.409955 -1.669829
96 -0.840720 -3.900299  2.461650  2.220469  0.446488
97 -0.757302 -4.520856  2.054356  1.009962  0.517251
98 -1.219320 -4.940810  0.214307  0.442335 -2.791174
99 -0.998472 -4.754834  1.869807 -0.122382 -0.427163

[100 rows x 5 columns]

In [48]:
### calculate lower CI (2.5%), upper CI (97.5%) and mean of each predictor coefficient
ci_lower = np.percentile(coef_df_2, 2.5, axis=0)
ci_upper = np.percentile(coef_df_2, 97.5, axis=0)
coef_mean = np.mean(coef_df_2, axis=0).to_numpy()

ci_results_df = pd.DataFrame({'Predictor': coef_df.drop(columns="Measels_Vac_Rate").columns,
                                            'Mean': coef_mean,
                                            'CI_Lower': ci_lower,
                                            'CI_Upper': ci_upper})

In [49]:
ci_results_df

  Predictor      Mean  CI_Lower  CI_Upper
0      PCA1 -0.874482 -1.446161 -0.342855
1      PCA2 -4.568743 -5.512594 -3.691972
2      PCA3  1.176979  0.099615  2.185013
3      PCA4  0.250619 -0.839290  1.502251
4      PCA5 -0.217064 -1.936490  1.420068

In [31]:
pca_model.explained_variance_ratio_

array([0.38714207, 0.14685255, 0.094867  , 0.05232196, 0.03486847])

## Running for real results for PCA

In [ ]:
all_ridge_percent_df5, ridge_pca5_r2, ridge_pca5_sig, y_ridge_pca5_results = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Ridge", num_components=5)
#all_ridge_percent_df5

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PC0,-0.874527,-1.447400,-0.314860,0.387142,Signficant
1,PC1,-4.536356,-5.519229,-3.565818,0.146853,Signficant
2,PC2,1.140400,-0.017415,2.251881,0.094867,Not Signficant
3,PC3,0.205182,-1.146569,1.663377,0.052322,Not Signficant
4,PC4,-0.144410,-2.027250,1.597074,0.034868,Not Signficant

In [13]:
ridge_pca5_r2

0.03444542661698835

In [ ]:
all_linear_percent_df5, linear_pca5_r2, linear_pca5_sig, y_linear_pca5_results = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Linear", num_components=5)
#all_linear_percent_df5

  Predictor      Mean  CI_Lower  CI_Upper Coeff Signficance
0      PCA0 -0.892752 -1.472313 -0.311534        Signficant
1      PCA1 -4.525461 -5.481831 -3.510365        Signficant
2      PCA2  1.154316  0.076503  2.237823        Signficant
3      PCA3  0.189697 -1.299022  1.702437    Not Signficant
4      PCA4 -0.144057 -2.037549  1.606355    Not Signficant

In [12]:
#number_components_array = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
#number_components_array = np.arange(2, 10+1)
number_components_array = np.arange(2, 35+1)

In [13]:
linear_results_dict = {}
ridge_results_dict = {}
results_r2_list = []
for n in number_components_array:
    all_linear_percent_df, linear_pca_r2, linear_pca_sig_r2, y_results_linear_pca = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Linear", num_components=n)
    linear_results_r2_list = []
    linear_results_r2_list.append(all_linear_percent_df)
    linear_results_r2_list.append(linear_pca_r2)
    linear_results_r2_list.append(linear_pca_sig_r2)
    linear_results_r2_list.append(y_results_linear_pca)
    linear_results_dict[f"{n}"] = linear_results_r2_list

    all_ridge_percent_df, ridge_pca_r2, ridge_pca_sig_r2, y_results_ridge_pca = bootstrap_confidence_interval_pca(1000, all_vac_set_no_gender_percent, model_type="Ridge", num_components=n)
    ridge_results_r2_list = []
    ridge_results_r2_list.append(all_ridge_percent_df)
    ridge_results_r2_list.append(ridge_pca_r2)
    ridge_results_r2_list.append(ridge_pca_sig_r2)
    ridge_results_r2_list.append(y_results_ridge_pca)
    ridge_results_dict[f"{n}"] = ridge_results_r2_list

In [20]:
linear_results_dict['2'][1]

0.03444557563194306

In [ ]:
linear_results_dict['4'][0][linear_results_dict['4'][0]['Coeff Signficance'] == 'Signficant']

,Predictor,Mean,CI_Lower,CI_Upper,Explained Variance,Coeff Signficance
0,PCA0,-0.883090,-1.453483,-0.318500,0.387142,Signficant
1,PCA1,-4.537578,-5.536254,-3.524958,0.146853,Signficant
2,PCA2,1.177385,0.134808,2.321960,0.094867,Signficant

In [15]:
for key in linear_results_dict.keys():
    cum_ev = linear_results_dict[key][0]['Explained Variance'].sum()
    sig_df = linear_results_dict[key][0][linear_results_dict[key][0]['Coeff Signficance'] == 'Signficant']
    cum_sig_ev = sig_df['Explained Variance'].sum()
    num_rows = len(sig_df.index)
    r2 = linear_results_dict[key][1]
    r2_sig = linear_results_dict[key][2]

    print(f"{key}: Total Expl = {cum_ev:.2f}, # of Sig PCs = {num_rows}, Sig Exp = {cum_sig_ev:.2f}, R2_OG = {r2:.3f}, R2_sig = {r2_sig:.3f}")

2: Total Expl = 0.53, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.036, R2_sig = 0.036
3: Total Expl = 0.63, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.032, R2_sig = 0.032
4: Total Expl = 0.68, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.028, R2_sig = 0.029
5: Total Expl = 0.72, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.024, R2_sig = 0.023
6: Total Expl = 0.74, # of Sig PCs = 4, Sig Exp = 0.66, R2_OG = 0.032, R2_sig = 0.033
7: Total Expl = 0.77, # of Sig PCs = 4, Sig Exp = 0.66, R2_OG = 0.036, R2_sig = 0.038
8: Total Expl = 0.79, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.036, R2_sig = 0.041
9: Total Expl = 0.80, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.029, R2_sig = 0.029
10: Total Expl = 0.81, # of Sig PCs = 5, Sig Exp = 0.59, R2_OG = 0.040, R2_sig = 0.035

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Linear", sig_feats=True)

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Linear")

In [ ]:
#linear_results_dict['25'][0].to_csv(f"../linear_regression_fit_results/pca25_linear_regression_fit.csv")
#linear_results_dict['35'][0].to_csv(f"../linear_regression_fit_results/pca35_linear_regression_fit.csv")

In [16]:
for key in ridge_results_dict.keys():
    cum_ev = ridge_results_dict[key][0]['Explained Variance'].sum()
    sig_df = ridge_results_dict[key][0][ridge_results_dict[key][0]['Coeff Signficance'] == 'Signficant']
    cum_sig_ev = sig_df['Explained Variance'].sum()
    num_rows = len(sig_df.index)
    r2 = ridge_results_dict[key][1]
    r2_sig = ridge_results_dict[key][2]

    print(f"{key}: Total Expl = {cum_ev:.2f}, # of Sig PCs = {num_rows}, Sig Exp = {cum_sig_ev:.2f}, R2_OG = {r2:.3f}, R2_sig = {r2_sig:.3f} ")

2: Total Expl = 0.53, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.023, R2_sig = 0.023
3: Total Expl = 0.63, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.044, R2_sig = 0.044
4: Total Expl = 0.68, # of Sig PCs = 2, Sig Exp = 0.53, R2_OG = 0.033, R2_sig = 0.034
5: Total Expl = 0.72, # of Sig PCs = 3, Sig Exp = 0.63, R2_OG = 0.049, R2_sig = 0.052
6: Total Expl = 0.74, # of Sig PCs = 3, Sig Exp = 0.56, R2_OG = 0.041, R2_sig = 0.041
7: Total Expl = 0.77, # of Sig PCs = 3, Sig Exp = 0.56, R2_OG = 0.064, R2_sig = 0.065
8: Total Expl = 0.79, # of Sig PCs = 5, Sig Exp = 0.68, R2_OG = 0.029, R2_sig = 0.031
9: Total Expl = 0.80, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.063, R2_sig = 0.060
10: Total Expl = 0.81, # of Sig PCs = 4, Sig Exp = 0.58, R2_OG = 0.054, R2_sig = 0.051

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Ridge", sig_feats=True)

In [ ]:
plot_vac_rates_predicted_actual(linear_results_dict["35"][3], reg_type="Ridge")

In [ ]:
#ridge_results_dict['25'][0].to_csv(f"../ridge_regression_fit_results/pca25_ridge_regression_fit.csv")
#ridge_results_dict['34'][0].to_csv(f"../ridge_regression_fit_results/pca34_ridge_regression_fit.csv")